name: CI


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs: 
  test:
    runs-on: ubuntu-latest

    strategy:                            # how I want this job to be executed
      fail-fast: false                   # look at note below
      matrix:                            # GitHub creates multiple versions of this job based on the values below, and they run IN PARALLEL (instead of creating seperate jobs for each py. version)
        python-version: ["3.1", "3.12"]  # Make one run for 3.11 and another for 3.12

  ## important matrix concept!!
  # By default, a matrix can cancel the remaining matrix jobs when one fails. To avoid this -> fail-fast: false
  #  fail-fast: false = If one version fails, the other must still finish. Do not let GitHub cancel it.

    steps:
      - name: Printing
        run: echo "studying CI/CD"         
    
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5    
        with: 
            python-version: ${{ matrix.python-version }}      # gitHub puts the value of this variable, in this case:  matrix.python-version=["3.1", "3.12"] 
            cache: "pip"
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run linter             
        run: flake8 . 

      - name: Run tests
        run: pytest -q --junitxml=report.xml   