name: CI


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Printing
        run: echo "studying CI/CD"
    


  